### ISSUE TITLE
The current chemfig code is broken, so PDF cannot be generated. Keep modifying the code

### ISSUE THREAD

**Issue by carmenchui** [py-chemist/web_apps#1]
Hi @py-chemist,

First off-- thank you for mol2chemfig web!  It's been a great tool to generate diagrams on the fly.
I've noticed that the tool is now throwing an error when generating the PDF on both your hosted site and my own local copy.  I was wondering which web service you are connecting to? I'm getting the following errors (in the screenshot):
![2018-03-23_12-36-05](https://user-images.githubusercontent.com/4117565/37841856-ff82ee12-2e96-11e8-84bf-306c64389b57.jpg)

![2018-03-23_12-34-28](https://user-images.githubusercontent.com/4117565/37841871-1419c60c-2e97-11e8-9f14-bced7ed69b89.jpg)

**Comment by py-chemist** [comment]
Hi Carmen,

Glad to hear that you found my site useful. I am very busy right now so
I'll get to you later with regard to local copy. I just fixed the
generation of pdf on my official website. Also, if the same error happens
again, feel free to use the second  version (under development, not
officially announced yet) of the same website. It can be found here
http://45.33.42.5/mol_2_chemfig/home.

Best,
Vitali

**Comment by carmenchui** [comment]
Hi Vitali,

Thank you so much for your quick reply and taking the time to fix this!  I can confirm that both versions can generate the pdf now without issues.

Thanks again,
Carmen

**Comment by py-chemist** [comment]
Hi Carmen,

Do you still want to use a local version of a website? If yes, how
comfortable are you with GNU/Linux? The reason I am asking is that I do not
know how difficult it will be to install all dependencies on Mac or
Windows. If you like, I can give you instructions how to fix pdf on
Gnu/Linux.

Best,
Vitali

**Comment by carmenchui** [comment]
Hi Vitali,

My local copy of mol2chemfig web is hosted on a Debian-based machine (RaspberryPi3); if you would like to pass me the instructions, I can try to take a look at them some time this week.

Regards,
Carmen

**Comment by py-chemist** [comment]
Hi Carmen,

I am very sorry for a late reply. Follow the instructions bellow and you
should be able to make mol2chemfig web work on Raspberry Pi (I use Ubuntu).

1. Install texlive

    sudo apt-get install texlive

2. Go to https://ctan.org/pkg/mol2chemfig?lang=en and download
mol2chemfig.zip

3. Download and extract the archive. Copy mol2chemfig.sty(located in tex
folder) to either /usr/share/texmf-texlive/tex/latex
or /usr/share/texmf/tex/latex/. I don't know which one Debian has (maybe a
different path to /tex/latex).

   cp mol2chemfig.sty /usr/share/texmf-texlive/tex/latex

4. Update libraries

    sudo mktexlsr

5. Open pdfgen.py file located in mol2chemfig directory and modify the
following line:

    m2pkg_path = '
/home/py-chemist/Projects/git_control/mol_2_chemfig/mol2chemfig'

make sure to indicate your full path to mol2chemfig directory.

6. Restart the server

At this point, a generated pdf should be displayed in the canvas on the
page.

Let me know if you run into problems.

Best,
Vitali

**Comment by carmenchui** [comment]
Hi Vitali,

No worries about the delayed reply!
My texlive distribution was in /usr/share/texlive/texmf-dist/tex/latex/ 

I managed to follow your instructions and the script is now able to generate the pdf without issues locally on my RaspberryPi (screenshot attached):
![2018-04-06_22-50-09](https://user-images.githubusercontent.com/4117565/38451056-d0c0ae5a-39f6-11e8-859c-407b91c4a244.jpg)

Since the script is now working as intended, I am going to go ahead and close this issue on Github.
Thank you again for taking the time to send me instructions!  It is much appreciated.

Regards,
Carmen

**Comment by py-chemist** [comment]
Great news! I am glad that it worked. Let me know if you have any other
questions.

Best,
Vitali
